# Generated by Django 4.0.6 on 2022-07-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=400)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('categorias', models.CharField(choices=[('urgente', 'Urgente'), ('importante', 'Importante'), ('Precisa ser feito', 'Precisa ser feito')], default='importante', max_length=25)),
                ('status', models.CharField(choices=[('concluido', 'Concluído'), ('pendente', 'Pendente'), ('adiado', 'Adiado')], default='pendente', max_length=25)),
            ],
        ),
    ]
